### ISSUE TITLE
Remove workaround for broken ConfirmPopup / Popover arrow positioning

### ISSUE THREAD

**Issue by multun** [SafeHavenMaps/safehaven#41]
The upgrade to primevue's 4.0.0-rc.2 broke ConfirmPopup / Popover arrow positioning, and we decided to upgrade anyway and just hide the arrows until our fix lands and gets released:  https://github.com/primefaces/primevue/pull/5934

Once it's done, this workaround can be removed https://github.com/SafeHavenMaps/safehaven/blob/d249b25db16cc3f3cadffa1134a6603a0369ff97/frontend/assets/main.css#L44-L54

**Comment by ghost** [comment]
Done
